[package]
name = "corepack"
version = "0.1.0"
authors = ["Jerome Rasky <jyrome.112@gmail.com>"]

[dependencies]
serde = { version = "*", git = "https://github.com/serde-rs/serde", default-features = false, features = ["collections"] }
byteorder = { version = "*", default-features = false }
