[package]
name = "corepack"
version = "0.2.0"
authors = ["Jerome Rasky <jyrome.112@gmail.com>"]
description = "A no_std support for messagepack in serde"
documentation = "https://docs.rs/corepack"
repository = "https://github.com/jrasky/corepack.git"
readme = "README.md"
keywords = ["messagepack", "binary", "encoding", "serialize"]
license = "MPL-2.0"

[dependencies]
serde = { version = "~0.9.8", default-features = false, features = ["collections"] }
byteorder = { version = "~1.0", default-features = false }

[dev-dependencies]
serde_derive = { version = "~0.9.8", features = ["unstable"] }

[features]
default = []

std = ["serde/std"]
