[package]
name = "corepack"
version = "0.1.0"
authors = ["Jerome Rasky <jyrome.112@gmail.com>"]
build = "build.rs"

[dependencies]
serde = { version = "0.8", default-features = false, features = ["collections"] }
byteorder = { version = "1.0", default-features = false }

[build-dependencies]
serde_codegen = { version = "0.8" }

[features]
default = []

std = ["serde/std"]
